<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form.PHP</title>
</head>

<body>


    <section class="flex">

        <div class="flex-menu">

            <form action="">

                <h2> Cadastre-se e tenha facilidade e descontos exclusivos </h2>

                <p> preencha o Formulario abaixo e entraremos em contato com você </p>

                <div class="input-single">
                    <input type="text" id="nome-box" class="input" name="nome" autocomplete="off" required>

                    <label for=""> Nome </label>

                </div>

                <div class="input-single">

                    <input type="text" id="sobrenome-box" class="input" name="sobrenome" autocomplete="off" required>

                    <label for="sobrenome-box"> Sobrenome</label>
                </div>

                <div class="">

                    <input type="text" id="email-box" class="input" name="email">
                    <label for=""> Email </label>
                </div>


                <div class="input-single">

                    <input type="text" id="senha-box" class="input" name="senha" autocomplete="off" required>
                    <label for=""> Senha </label>
                </div>

            </form>
        </div>
    </section>




</body>

</html>